f=file.choose()  # data set selection
f1=read.csv(f) 
f2<-f1
class(f2) # to check the class
str(f2) # to check the structure
summary(f2) # summarizing the dataset
for(i in 1:nrow(f2))
 for(j in 1:ncol(f2))
if(f2[i,j]=="None")
 f2[i,j]=NA
colMeans(is.na(f2))  # missing per cent per column
f2<-f2[,-c(12,6)]  # removing the columns with more per cent of missing values
pMiss <- function(x){sum(is.na(x))/length(x)*100}
apply(f2,2,pMiss)  #missing values in  per cent per column
apply(f2,1,pMiss)  #missing  values in  per cent per rows
library(mice)  # print the pattern of missing values and for imputation
md.pattern(f2)
library(VIM)
aggr_plot <- aggr(f2, col=c('navyblue','red'), numbers=TRUE, sortVars=TRUE, labels=names(data), cex.axis=.7, gap=3, ylab=c("Histogram of missing data","Pattern"))
f_new <- f2[,-c(1,2)]  #remove dates
head(f_new)
# converting the values into numeric  format
at <- as.numeric(as.character(f_new$AT))
pm10 <- as.numeric(as.character(f_new$PM10))
pm2.5 <- as.numeric(as.character(f_new$PM2.5))
bp <- as.numeric(as.character(f_new$BP))
wd <- as.numeric(as.character(f_new$WD))
ws <- as.numeric(as.character(f_new$WS))
rh <- as.numeric(as.character(f_new$RH))
sr <- as.numeric(as.character(f_new$SR))
benzene <- as.numeric(as.character(f_new$Benzene))
toluene <- as.numeric(as.character(f_new$Toluene))
nh3 <- as.numeric(as.character(f_new$NH3))
no <- as.numeric(as.character(f_new$NO))
no2 <- as.numeric(as.character(f_new$NO2))
nox <- as.numeric(as.character(f_new$NOx))
ozone <- as.numeric(as.character(f_new$Ozone))
so2 <- as.numeric(as.character(f_new$SO2))
co <- as.numeric(as.character(f_new$CO))
f_comb <- data.frame(cbind(at,pm10,pm2.5,bp,wd,ws,rh,sr,benzene,toluene,nh3,no,no2,nox,ozone,so2,co))
f_comb$From.Date <- f2$From.Date
f_comb$To.Date <- f2$To.Date
head(f_comb)
f11<-f_comb
f11[ , 18] <- as.character(f11[ , 18])
f11[ , 19] <- as.character(f11[ , 19])
summary(f11)
head(f11)
library(splitstackshape)   # to split the date string into date and time  
f11<-cSplit(f11,"From.Date", " ")
head(f11)
f11<-cSplit(f11,"To.Date", " ")
head(f11)
summary(f11)
levels(f11$From.Date_1) # to check the various levels of date
head(f11)
# to make all the dates of same format
t_to <- as.data.frame(sapply(f11$To.Date_1,gsub,pattern="-",replacement="/"))
library(dplyr);
library(lubridate)
f4 <- data.frame()
# to calculate the average of per day
f4 <- f11 %>% 
  mutate(
d =as.POSIXct(d,format="%d/%m/%Y ")) %>%
group_by(date(d)) %>%
summarise(meanCO=mean(co,na.rm=TRUE),meanNO=mean(no,na.rm=TRUE),meanNO2=mean(no2,na.rm=TRUE),meanRH=mean(rh,na.rm=TRUE),meanSR=mean(sr,na.rm=TRUE),meanSO2=mean(so2,na.rm=TRUE),meanWD=mean(wd,na.rm=TRUE) ,meanAT=mean(at,na.rm = TRUE),
meanBenzene=mean(benzene,na.rm = TRUE),meanToluene=mean(toluene,na.rm = TRUE),meanNOx=mean(nox,na.rm = TRUE), meanPM10=mean(pm10,na.rm = TRUE),meanPM2.5=mean(pm2.5,na.rm = TRUE),meanNH3=mean(nh3,na.rm = TRUE),meanBP=mean(bp,na.rm = TRUE),meanOzone=mean(ozone,na.rm = TRUE),meanWS=mean(ws,na.rm = TRUE)        
  ) %>% as.data.frame
# removing  date (d)  in f4
f5 <- f4[-c(1)]
f6 <- f5
head(f6)
# replacing  with the missing values with median
average_missing <- apply(f6[,colnames(f6) ], 2, median, na.rm =  TRUE)
for(i in 1:ncol(f6))
 for(j in 1:nrow(f6))
 if(is.na(f6[j,i]))
 f6[j,i] <- average_missing[i]
plot(f6$meanCO)
removeOutliers = function(x) {  # function to remove outliers 
  qnt = quantile(x, probs=c(.25, .75))
   iqt = 1.5 * IQR(x)
  # Apply on a copy of the original data
  y = x 
  y[x < (qnt[1] - iqt)] = NA
  y[x > (qnt[2] + iqt)] = NA
 return (y) 
}

aco <- removeOutliers(f6$meanCO)
plot(aco)
 plot(f6$meanNO)
ano <- removeOutliers(f6$meanNO)
plot(ano)
plot(f6$meanNO2)
ano2 <- removeOutliers(f6$meanNO2)
plot(ano2)
plot(f6$meanRH)
arh <- removeOutliers(f6$meanRH)
plot(arh)
plot(f6$meanSR)
asr <- removeOutliers(f6$meanSR)
plot(asr)
plot(f6$meanSO2)
aso2 <- removeOutliers(f6$meanSO2)
plot(aso2)
plot(f6$meanAT)
aat <- removeOutliers(f6$meanAT)
plot(aat)
plot(f6$meanWD)
awd <- removeOutliers(f6$meanWD)
plot(awd)

plot(f6$meanBenzene)
ab <- removeOutliers(f6$meanBenzene)
plot(ab)
plot(f6$meanToluene)
at <- removeOutliers(f6$meanToluene)
plot(at)
plot(f6$meanNOx)
anox <- removeOutliers(f6$meanNOx)
plot(anox)
plot(f6$meanPM10)
apm10 <- removeOutliers(f6$meanPM10)
plot(apm10)
plot(f6$meanPM2.5)
apm2.5 <- removeOutliers(f6$meanPM2.5)
plot(apm2.5)
plot(f6$meanNH3)
anh3 <- removeOutliers(f6$meanNH3)
plot(anh3)
plot(f6$meanBP)
abp <- removeOutliers(f6$meanBP)
plot(abp)
plot(f6$meanOzone)
aozone <- removeOutliers(f6$meanOzone)
plot(aozone)

plot(f6$meanWS)
aws <- removeOutliers(f6$meanWS)
plot(aws)
clear <- data.frame(aco,ano,ano2,arh,asr,aso2,awd,aat,ab,at,anox,apm10,apm2.5,anh3,abp,aozone,aws)
tempData <- mice(clear,m=5,maxit=50,meth='pmm',seed=500)   # to impute 5 diiferent set of values 
summary(tempData)
completedData <- complete(tempData,5) # change between 1 to 5 to see imputed sets
head(completedData)
res_data <- completedData
boxplot(res_data$aco)
boxplot(res_data$ano)
boxplot(res_data$ano2)
boxplot(res_data$arh)
boxplot(res_data$asr)
boxplot(res_data$aso2)
boxplot(res_data$awd)
boxplot(res_data$aat)
boxplot(res_data$ab)
boxplot(res_data$at)
boxplot(res_data$anox)
boxplot(res_data$apm10)
boxplot(res_data$apm2.5) # outlier
boxplot(res_data$anh3) # outliers
boxplot(res_data$abp)
boxplot(res_data$aozone)
boxplot(res_data$aws)
library(e1071) # to see skewness and transforming as required
skewness(res_data$at)
res_data$at<-(res_data$at)^0.2
skewness(res_data$at)
skewness(res_data$aco)
res_data$aco<-(res_data$aco)^0.02
skewness(res_data$aco)
skewness(res_data$ano)
res_data$ano<-(res_data$ano)^0.2
skewness(res_data$ano)
skewness(res_data$ano2)
res_data$ano2<-(res_data$ano2)^0.02
skewness(res_data$ano2)
skewness(res_data$arh)
res_data$ah<-(res_data$arh)
skewness(res_data$arh)
skewness(res_data$asr)
res_data$asr<-(res_data$asr)
skewness(res_data$asr)
skewness(res_data$aso2)
res_data$aso2<-(res_data$aso2)^0.2
skewness(res_data$aso2)
skewness(res_data$awd)
res_data$awd<-(res_data$awd)
skewness(res_data$awd)
skewness(res_data$aat)
res_data$aat <- (res_data$aat)^2
skewness(res_data$aat)
skewness(res_data$ab)
res_data$ab<-(res_data$ab)^0.5
skewness(res_data$ab)
skewness(res_data$anox)
res_data$anox<-(res_data$anox)^0.02
skewness(res_data$anox)
skewness(res_data$apm10)
res_data$apm10<-(res_data$apm10)^0.5
skewness(res_data$apm10)
skewness(res_data$apm2.5)
res_data$apm2.5<-(res_data$apm2.5)^0.02
skewness(res_data$apm2.5)
skewness(res_data$anh3)
res_data$anh3<-(res_data$anh3)^0.04
skewness(res_data$anh3)
skewness(res_data$abp)
res_data$abp<-(res_data$abp)
skewness(res_data$abp)
skewness(res_data$aozone)
res_data$aozone<-(res_data$aozone)^0.2
skewness(res_data$aozone)

skewness(res_data$aws)
res_data$aws<-(res_data$aws)
skewness(res_data$aws)
train1 <- res_data[1:250,]
tail(train1)
test1 <- res_data[251:282,]
tail(test1)
library(forecast)  # for arima function
library(tseries)  
tss <- ts(train1$aco) # creating time series object
acf(diff(log(tss)))
pacf(diff(log(tss)))
adf.test(diff(log(tss)))
kpss.test(diff(log(tss)))
plot(diff(log(tss)))
auto.arima(tss)
fit11 <- arima(tss,order=c(1,0,1))
accuracy(fit11)
qqnorm(fit11$residuals)
qqline(fit11$residuals)
forecast(fit11,31)
test1$aco
plot(forecast(fit11,31),xlab="year",ylab="polutant")

tss <- ts(train1$ano)
acf(diff(log(tss)))
pacf(diff(log(tss)))
adf.test(diff(log(tss)))
kpss.test(diff(log(tss)))
plot(diff(log(tss)))
auto.arima(tss)
fit11 <- arima(tss,order=c(1,1,1))
accuracy(fit11)
qqnorm(fit11$residuals)
qqline(fit11$residuals)
forecast(fit11,31)
test1$ano
plot(forecast(fit11,31),xlab="year",ylab="polutant")
tss <- ts(train1$ano2)
acf(diff(log(tss)))
pacf(diff(log(tss)))
adf.test(diff(log(tss)))
kpss.test(diff(log(tss)))
plot(diff(log(tss)))
auto.arima(tss)
fit11 <- arima(tss,order=c(1,1,1))
accuracy(fit11)
qqnorm(fit11$residuals)
qqline(fit11$residuals)
forecast(fit11,31)
test1$ano2
plot(forecast(fit11,31),xlab="year",ylab="polutant")
tss <- ts(train1$arh)
acf(diff(log(tss)))
pacf(diff(log(tss)))
adf.test(diff(log(tss)))
kpss.test(diff(log(tss)))
plot(diff(log(tss)))
auto.arima(tss)
fit11 <- arima(tss,order=c(2,1,2))
accuracy(fit11)
qqnorm(fit11$residuals)
qqline(fit11$residuals)
forecast(fit11,31)
test1$arh
plot(forecast(fit11,31),xlab="year",ylab="polutant")
tss <- ts(train1$asr)
acf(diff(log(tss)))
pacf(diff(log(tss)))
adf.test(diff(log(tss)))
kpss.test(diff(log(tss)))
plot(diff(log(tss)))
auto.arima(tss)
fit11 <- arima(tss,order=c(1,1,1))
accuracy(fit11)
qqnorm(fit11$residuals)
qqline(fit11$residuals)
forecast(fit11,31)
test1$asr
plot(forecast(fit11,10),xlab="year",ylab="polutant")
tss <- ts(train1$aso2)
acf(diff(log(tss)))
pacf(diff(log(tss)))
adf.test(diff(log(tss)))
kpss.test(diff(log(tss)))
plot(diff(log(tss)))
auto.arima(tss)
fit11 <- arima(tss,order=c(1,1,1))
accuracy(fit11)
qqnorm(fit11$residuals)
qqline(fit11$residuals)
forecast(fit11,31)
#head(test1)
test1$aso2
plot(forecast(fit11,31),xlab="year",ylab="polutant")
tss <- ts(train1$WDmean)
acf(diff(log(tss)))
pacf(diff(log(tss)))
adf.test(diff(log(tss)))
kpss.test(diff(log(tss)))
plot(diff(log(tss)))
auto.arima(tss)
fit11 <- arima(tss,order=c(2,1,2))
accuracy(fit11)
qqnorm(fit11$residuals)
qqline(fit11$residuals)
forecast(fit11,31)
test1$WDmean
plot(forecast(fit11,31),xlab="year",ylab="polutant")
tss <- ts(train1$ATmean)
acf(diff(log(tss)))
pacf(diff(log(tss)))
adf.test(diff(log(tss)))
kpss.test(diff(log(tss)))
plot(diff(log(tss)))
auto.arima(tss)
fit11 <- arima(tss,order=c(2,1,1))
accuracy(fit11)
qqnorm(fit11$residuals)
qqline(fit11$residuals)
forecast(fit11,31)
test1$ATmean
plot(forecast(fit11,31),xlab="year",ylab="polutant")
tss <- ts(train1$Benzenemean)
acf(diff(log(tss)))
pacf(diff(log(tss)))
adf.test(diff(log(tss)))
kpss.test(diff(log(tss)))
plot(diff(log(tss)))
auto.arima(tss)
fit11 <- arima(tss,order=c(1,1,1))
accuracy(fit11)
qqnorm(fit11$residuals)
qqline(fit11$residuals)
forecast(fit11,31)
test1$Benzenemean
plot(forecast(fit11,31),xlab="year",ylab="polutant")
tss <- ts(train1$Toluenemean)
acf(diff(log(tss)))
pacf(diff(log(tss)))
adf.test(diff(log(tss)))
kpss.test(diff(log(tss)))
plot(diff(log(tss)))
auto.arima(tss)
fit11 <- arima(tss,order=c(0,1,1))
accuracy(fit11)
qqnorm(fit11$residuals)
qqline(fit11$residuals)
forecast(fit11,31)
test1$Toluenemean
plot(forecast(fit11,31),xlab="year",ylab="polutant")
tss <- ts(train1$NOxmean)
acf(diff(log(tss)))
pacf(diff(log(tss)))
adf.test(diff(log(tss)))
kpss.test(diff(log(tss)))
plot(diff(log(tss)))
auto.arima(tss)
fit11 <- arima(tss,order=c(1,1,2))
accuracy(fit11)
qqnorm(fit11$residuals)
qqline(fit11$residuals)
forecast(fit11,31)
test1$NOxmean
plot(forecast(fit11,31),xlab="year",ylab="polutant")
tss <- ts(train1$PM10mean)
acf(diff(log(tss)))
pacf(diff(log(tss)))
adf.test(diff(log(tss)))
kpss.test(diff(log(tss)))
plot(diff(log(tss)))
auto.arima(tss)
fit11 <- arima(tss,order=c(0,1,0))
accuracy(fit11)
qqnorm(fit11$residuals)
qqline(fit11$residuals)
forecast(fit11,31)
test1$PM10mean
plot(forecast(fit11,31),xlab="year",ylab="polutant")
tss <- ts(train1$PM2.5mean)
acf(diff(log(tss)))
pacf(diff(log(tss)))
adf.test(diff(log(tss)))
kpss.test(diff(log(tss)))
plot(diff(log(tss)))
auto.arima(tss)
fit11 <- arima(tss,order=c(1,1,1))
accuracy(fit11)
qqnorm(fit11$residuals)
qqline(fit11$residuals)
forecast(fit11,31)
test1$PM2.5mean
plot(forecast(fit11,31),xlab="year",ylab="polutant")

tss <- ts(train1$NH3mean)
acf(diff(log(tss)))
pacf(diff(log(tss)))
adf.test(diff(log(tss)))
kpss.test(diff(log(tss)))
plot(diff(log(tss)))
auto.arima(tss)
fit11 <- arima(tss,order=c(1,1,1))
accuracy(fit11)
qqnorm(fit11$residuals)
qqline(fit11$residuals)
forecast(fit11,31)
test1$NH3mean
plot(forecast(fit11,31),xlab="year",ylab="polutant")
tss <- ts(train1$BPmean)
acf(diff(log(tss)))
pacf(diff(log(tss)))
adf.test(diff(log(tss)))
kpss.test(diff(log(tss)))
plot(diff(log(tss)))
auto.arima(tss)
fit11 <- arima(tss,order=c(2,1,1))
accuracy(fit11)
qqnorm(fit11$residuals)
qqline(fit11$residuals)
forecast(fit11,31)
test1$BPmean
plot(forecast(fit11,31),xlab="year",ylab="polutant")
tss <- ts(train1$Ozonemean)
acf(diff(log(tss)))
pacf(diff(log(tss)))
adf.test(diff(log(tss)))
kpss.test(diff(log(tss)))
plot(diff(log(tss)))
auto.arima(tss)
fit11 <- arima(tss,order=c(4,1,2))
accuracy(fit11)
qqnorm(fit11$residuals)
qqline(fit11$residuals)
forecast(fit11,31)
test1$Ozonemean
plot(forecast(fit11,31),xlab="year",ylab="polutant")
tss <- ts(train1$WSmean)
acf(diff(log(tss)))
pacf(diff(log(tss)))
adf.test(diff(log(tss)))
kpss.test(diff(log(tss)))
plot(diff(log(tss)))
auto.arima(tss)
fit11 <- arima(tss,order=c(1,1,1))
accuracy(fit11)
qqnorm(fit11$residuals)
qqline(fit11$residuals)
forecast(fit11,31)
test1$WSmean
plot(forecast(fit11,31),xlab="year",ylab="polutant")

